# add stages here 
# stages:
#   stage_name:
#     cmd: python src/stage_01______.py
#     deps:
#     - src/stage_01______.py
#     outs:
#     - output_data_of_file_path

stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py
    deps:
      - src/stage_01_prepare.py
      - data/data.xml
      - src/utils/common.py
      - src/utils/data_mgmt.py
      - config/config.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
